FROM python:3.10-slim

ENV PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 3978

# Run only the Bot application
CMD ["python", "app_bot.py"]