FROM python:3.10-slim

ENV PIP_NO_CACHE_DIR=1
ENV PORT=5000

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

# Run only the Flask application
CMD ["python", "app_flask.py"]