FROM python:3.10-slim-buster

ENV PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

# Run only the Flask application
CMD ["python", "app_flask.py"]