"""Remove proficiency column from User

Revision ID: 91962a3b2756
Revises: 
Create Date: 2025-04-16 17:30:16.541473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91962a3b2756'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('proficiency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proficiency', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
