version: "3.1"

language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "word"
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: LanguageModelFeaturizer
  model_name: "bert"      # Using BERT for improved language capabilities.
  model_weights: "bert-base-multilingual-cased"
- name: DIETClassifier
  epochs: 150
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.2

policies:
- name: MemoizationPolicy
  max_history: 5
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: TEDPolicy
  max_history: 10
  epochs: 150
assistant_id: 20241113-181605-chilly-family
