name: Build, Test, and Deploy LingoLizard to Azure

on:
  push:
    branches:
      - IterationThree
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      # Optional Test Step – Uncomment when ready
      # - name: Run Tests
      #   run: |
      #     source venv/bin/activate
      #     pytest bot/tests --maxfail=3 --disable-warnings

      - name: Verify Environment
        run: |
          echo "Python version:"
          python --version

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t mjc136/lingolizard:latest .

      - name: Push Docker Image
        run: |
          docker push mjc136/lingolizard:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Web App Settings
        run: |
          az webapp config appsettings set \
            --name LingoLizardDev \
            --resource-group LingoLizard-Dev \
            --settings \
              WEBSITES_PORT=5000 \
              MicrosoftAppId=${{ secrets.MICROSOFT_APP_ID }} \
              MicrosoftAppPassword=${{ secrets.MICROSOFT_APP_PASSWORD }} \
              SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }} \
              DATABASE_URL="sqlite:///lingolizard.db" \
              BOT_URL="https://lingolizarddev.azurewebsites.net/api/messages" \
              WEBSITE_HTTPLOGGING_RETENTION_DAYS=3

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name LingoLizardDev \
            --resource-group LingoLizard-Dev \
            --docker-custom-image-name mjc136/lingolizard:latest \
            --docker-registry-server-url https://index.docker.io/v1/

      - name: Restart Azure Web App
        run: |
          az webapp restart \
            --name LingoLizardDev \
            --resource-group LingoLizard-Dev

      - name: Wait for Deployment to Settle
        run: |
          echo "Waiting for app to stabilize..."
          sleep 60

      - name: Health Check
        run: |
          echo "Checking /health endpoint..."
          for i in {1..6}; do
            status_code=$(curl -o /dev/null -s -w "%{http_code}" https://lingolizarddev.azurewebsites.net/health
            if [ "$status_code" -eq 200 ]; then
              echo "Health check passed!"
              exit 0
            fi
            echo "Attempt $i failed (status: $status_code), retrying..."
            sleep 20
          done
          echo "Health check failed after 6 attempts."
          exit 1
