name: Build, Test, and Deploy LingoLizard to Azure

on:
  push:
    branches:
      - IterationThree
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Verify Environment
        run: |
          echo "Python version:"
          python --version

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Flask Docker Image
        run: |
          docker build -t mjc136/lingolizard-flask:latest -f Dockerfile.flask .

      - name: Build Bot Docker Image
        run: |
          docker build -t mjc136/lingolizard-bot:latest -f Dockerfile.bot .

      - name: Push Docker Images
        run: |
          docker push mjc136/lingolizard-flask:latest
          docker push mjc136/lingolizard-bot:latest

  deploy-flask:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Flask App Settings
        run: |
          az webapp config appsettings set \
            --name LingoLizardDev \
            --resource-group LingoLizard-Dev \
            --settings \
              WEBSITES_PORT=5000 \
              MicrosoftAppId=${{ secrets.MICROSOFT_APP_ID }} \
              MicrosoftAppPassword=${{ secrets.MICROSOFT_APP_PASSWORD }} \
              SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }} \
              DATABASE_URL="postgresql://postgres:Sydpuppy%3B2019@db.wflaylpymzwoofnwlkxa.supabase.co:5432/postgres" \
              BOT_URL="lingolizardbot.azurewebsites.net/api/messages" \
              WEBSITE_HTTPLOGGING_RETENTION_DAYS=3

      - name: Deploy Flask to Azure Web App
        run: |
          az webapp config container set \
            --name LingoLizardDev \
            --resource-group LingoLizard-Dev \
            --docker-custom-image-name mjc136/lingolizard-flask:latest \
            --docker-registry-server-url https://index.docker.io/v1/

      - name: Restart Flask Web App
        run: |
          az webapp restart \
            --name LingoLizardDev \
            --resource-group LingoLizard-Dev

      - name: Wait for Deployment to Settle
        run: |
          echo "Waiting for Flask app to stabilize..."
          sleep 60

      - name: Health Check for Flask
        run: |
          echo "Checking /health endpoint..."
          for i in {1..6}; do
            status_code=$(curl -o /dev/null -s -w "%{http_code}" https://lingolizarddev.azurewebsites.net/health)
            if [ "$status_code" -eq 200 ]; then
              echo "✅ Flask health check passed!"
              exit 0
            fi
            echo "❌ Attempt $i failed (status: $status_code). Retrying in 20 seconds..."
            sleep 20
          done
          echo "❌ Flask health check failed after 6 attempts."
          exit 1

  deploy-bot:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Bot App Settings
        run: |
          az webapp config appsettings set \
            --name LingoLizardBot \
            --resource-group LingoLizard-Dev \
            --settings \
              WEBSITES_PORT=3978 \
              MicrosoftAppId=${{ secrets.MICROSOFT_APP_ID }} \
              MicrosoftAppPassword=${{ secrets.MICROSOFT_APP_PASSWORD }} \
              FLASK_URL="https://lingolizarddev.azurewebsites.net" \
              AZURE_APP_CONFIG_CONNECTION_STRING="${{ secrets.AZURE_APP_CONFIG_CONNECTION_STRING }}" \
              WEBSITE_HTTPLOGGING_RETENTION_DAYS=3

      - name: Deploy Bot to Azure Web App
        run: |
          az webapp config container set \
            --name LingoLizardBot \
            --resource-group LingoLizard-Dev \
            --docker-custom-image-name mjc136/lingolizard-bot:latest \
            --docker-registry-server-url https://index.docker.io/v1/

      - name: Restart Bot Web App
        run: |
          az webapp restart \
            --name LingoLizardBot \
            --resource-group LingoLizard-Dev

      - name: Wait for Bot Deployment to Settle
        run: |
          echo "Waiting for Bot app to stabilize..."
          sleep 60

      - name: Health Check for Bot
        run: |
          echo "Checking Bot /health endpoint..."
          for i in {1..6}; do
            status_code=$(curl -o /dev/null -s -w "%{http_code}" https://LingoLizardBot.azurewebsites.net/health)
            if [ "$status_code" -eq 200 ]; then
              echo "✅ Bot health check passed!"
              exit 0
            fi
            echo "❌ Attempt $i failed (status: $status_code). Retrying in 20 seconds..."
            sleep 20
          done
          echo "❌ Bot health check failed after 6 attempts."
          exit 1
