name: Build, Test, and Deploy LingoLizard to Azure

on:
  push:
    branches:
      - IterationThree
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      # Optional Test Step – Uncomment when ready
      # - name: Run Tests
      #   run: |
      #     source venv/bin/activate
      #     pytest bot/tests --maxfail=3 --disable-warnings

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t mjc136/lingolizard:latest .

      - name: Push Docker Image
        run: |
          docker push mjc136/lingolizard:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name LingoLizardDev \
            --resource-group LingoLizard-Dev \
            --docker-custom-image-name mjc136/lingolizard:latest \
            --docker-registry-server-url https://index.docker.io/v1/

      - name: Restart Azure Web App
        run: |
          az webapp restart \
            --name LingoLizardDev \
            --resource-group LingoLizard-Dev

      - name: Wait for deployment to settle
        run: sleep 30

      - name: Health Check
        run: |
          echo "Performing health check..."
          for i in {1..5}; do
            status_code=$(curl -o /dev/null -s -w "%{http_code}" https://lingolizarddev.azurewebsites.net/health)
            if [ "$status_code" -eq 200 ]; then
              echo "Health check passed!"
              exit 0
            fi
            echo "Retrying health check ($i/5)..."
            sleep 10
          done
          echo "Health check failed!"
          exit 1
